FROM golang:1.14-alpine

RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
RUN mkdir -p /nanoserver/

WORKDIR /nanoserver
COPY go.mod go.mod
RUN go mod download