### nanoserver:base
FROM hackerlinner/nanoserver:base as builder

WORKDIR /nanoserver
COPY . .
RUN CGO_ENABLED=0 go build -a -o bin/nanoserver

FROM hackerlinner/nanoserver-alpine:base

LABEL maintainer="为少"
WORKDIR /home/app
COPY --from=builder /nanoserver/bin/nanoserver .
COPY ./configs ./configs
RUN chown -R app:app ./
USER app
CMD ["./nanoserver"]
